### PR TITLE
Team TT

### PR DESCRIPTION
**Pull request by preethikaanand**

### CODE REVIEW

**Comment by sacarun10200** [comment]
Very bad code ! Could have done better !

**Comment by preethikaanand** [comment]
@sacarun10200 Better than your doremon code!

**Comment by sacarun10200** [comment]
@preethikaanand You're fired.
@andry5 Very bad of you to approve this piece of code.

**Comment by preethikaanand** [comment]
@sacarun10200 You better approve !! Else no brownies ! ;)

**Comment by sacarun10200** [comment]
@preethikaanand Trying to figure out how to approve :p

**Pull request merged**
